name: Increment Counter

on:
  schedule:
    - cron: '30 1 * * *' # Runs daily at 1:30 AM UTC (9:30 PM Atlantic Time)
  workflow_dispatch: # Add this to enable manual runs

jobs:
  increment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run increment script
        run: |
          chmod +x increment.sh
          ./increment.sh

      - name: Commit and push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "usr-neo"
          git config user.email "vaibhavmishra5g@gmail.com"
          git add counter.txt
          git commit -m "Incremented counter to $(cat counter.txt)"
          git push https://$PAT_TOKEN@github.com/usr-neo/kbt.git HEAD:main
